version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${DB_NAME:-crm_production}
      POSTGRES_USER: ${DB_USER:-crm_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-crm_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - crm-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-crm_user}"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - crm-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # API Gateway
  api-gateway:
    build: ./api_gateway
    ports:
      - "8000:8000"
    environment:
      - DEBUG=${DEBUG:-False}
      - DJANGO_SETTINGS_MODULE=api_gateway.settings
      - SECRET_KEY=${SECRET_KEY}
      - DB_HOST=postgres
      - DB_NAME=${DB_NAME:-crm_production}
      - DB_USER=${DB_USER:-crm_user}
      - DB_PASSWORD=${DB_PASSWORD:-crm_password}
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      user-service:
        condition: service_started
      zayavki-service:
        condition: service_started
      finance-service:
        condition: service_started
    networks:
      - crm-network

  # User Service
  user-service:
    build: ./user_service
    ports:
      - "8001:8001"
    environment:
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=usersvc.settings
    volumes:
      - user_data:/app/data
    networks:
      - crm-network

  # Zayavki Service
  zayavki-service:
    build: ./zayavki_service
    ports:
      - "8002:8002"
    environment:
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=zayavkisvc.settings
    volumes:
      - zayavki_data:/app/data
    networks:
      - crm-network

  # Finance Service
  finance-service:
    build: ./financesvc
    ports:
      - "8003:8003"
    environment:
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=financesvc.settings
    volumes:
      - finance_data:/app/data
    networks:
      - crm-network

  # Nginx с SSL (для production)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl_certs:/etc/nginx/ssl:ro
    depends_on:
      - api-gateway
    networks:
      - crm-network

volumes:
  postgres_data:
  redis_data:
  user_data:
  zayavki_data:
  finance_data:

networks:
  crm-network:
    driver: bridge 