version: '3.9'

services:
  user_service:
    build: ./user_service
    env_file:
      - ./user_service/.env.example
    ports:
      - "8001:8000"
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: user_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - user_service_pgdata:/var/lib/postgresql/data

volumes:
  user_service_pgdata: 