version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${DB_NAME:-crm_production}
      POSTGRES_USER: ${DB_USER:-crm_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-1740}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - crm-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-crm_user}"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - crm-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # API Gateway
  api-gateway:
    build: ./api_gateway
    ports:
      - "8000:8000"
    environment:
      - DEBUG=${DEBUG:-False}
      - DJANGO_SETTINGS_MODULE=api_gateway.settings
      - SECRET_KEY=${SECRET_KEY}
      - DB_HOST=postgres
      - DB_NAME=${DB_NAME:-crm_production}
      - DB_USER=${DB_USER:-crm_user}
      - DB_PASSWORD=${DB_PASSWORD:-1740}
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - crm-network

  # User Service
  user-service:
    build: ./user_service
    ports:
      - "8001:8001"
    environment:
      - DEBUG=${DEBUG:-False}
      - DJANGO_SETTINGS_MODULE=usersvc.settings
      - SECRET_KEY=${SECRET_KEY}
      - DB_HOST=postgres
      - DB_NAME=${DB_NAME:-crm_production}
      - DB_USER=${DB_USER:-crm_user}
      - DB_PASSWORD=${DB_PASSWORD:-1740}
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - user_data:/app/data
    networks:
      - crm-network

  # Zayavki Service
  zayavki-service:
    build: ./zayavki_service
    ports:
      - "8002:8002"
    environment:
      - DEBUG=${DEBUG:-False}
      - DJANGO_SETTINGS_MODULE=zayavkisvc.settings
      - SECRET_KEY=${SECRET_KEY}
      - DB_HOST=postgres
      - DB_NAME=${DB_NAME:-crm_production}
      - DB_USER=${DB_USER:-crm_user}
      - DB_PASSWORD=${DB_PASSWORD:-1740}
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - zayavki_data:/app/data
    networks:
      - crm-network

  # Finance Service
  finance-service:
    build: ./financesvc
    ports:
      - "8003:8003"
    environment:
      - DEBUG=${DEBUG:-False}
      - DJANGO_SETTINGS_MODULE=financesvc.settings
      - SECRET_KEY=${SECRET_KEY}
      - DB_HOST=postgres
      - DB_NAME=${DB_NAME:-crm_production}
      - DB_USER=${DB_USER:-crm_user}
      - DB_PASSWORD=${DB_PASSWORD:-1740}
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - finance_data:/app/data
    networks:
      - crm-network

  # Frontend (React приложение)
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://crm.lead-schem.ru/api
      - REACT_APP_ENV=production
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    networks:
      - crm-network
    depends_on:
      - api-gateway

  # Nginx (без SSL для разработки)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api-gateway
      - frontend
    networks:
      - crm-network

volumes:
  postgres_data:
  redis_data:
  user_data:
  zayavki_data:
  finance_data:

networks:
  crm-network:
    driver: bridge 