# Generated by Django 5.2.4 on 2025-07-05 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('status', models.CharField(choices=[('pending', 'Ожидает перевод'), ('checking', 'Отправлено на проверку'), ('confirmed', 'Подтверждено')], default='pending', max_length=20, verbose_name='Статус выплаты')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий руководителя')),
                ('file', models.FileField(blank=True, null=True, upload_to='payout_cheques/', verbose_name='Чек перевода')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Выплата мастеру',
                'verbose_name_plural': 'Выплаты мастерам',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='zayavkafile',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Файл заявки', 'verbose_name_plural': 'Файлы заявок'},
        ),
        migrations.RemoveIndex(
            model_name='phonegoroda',
            name='core_phoneg_phone_949404_idx',
        ),
        migrations.RemoveIndex(
            model_name='phonegoroda',
            name='core_phoneg_gorod_i_da766d_idx',
        ),
        migrations.RemoveIndex(
            model_name='zayavki',
            name='core_zayavk_rk_id_fc6a5a_idx',
        ),
        migrations.RemoveIndex(
            model_name='zayavki',
            name='core_zayavk_tip_zay_522047_idx',
        ),
        migrations.RemoveIndex(
            model_name='zayavki',
            name='core_zayavk_phone_c_afa1b6_idx',
        ),
        migrations.RemoveIndex(
            model_name='zayavki',
            name='core_zayavk_status_158b0f_idx',
        ),
        migrations.RemoveIndex(
            model_name='zayavki',
            name='core_zayavk_master__1b8dea_idx',
        ),
        migrations.RemoveIndex(
            model_name='zayavki',
            name='core_zayavk_rk_id_70a4eb_idx',
        ),
        migrations.AlterField(
            model_name='master',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='master',
            name='passport',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Паспорт'),
        ),
        migrations.AlterField(
            model_name='zayavki',
            name='status',
            field=models.CharField(choices=[('Звонит', 'Звонит'), ('Ожидает', 'Ожидает'), ('Ожидает Принятия', 'Ожидает Принятия'), ('Принял', 'Принял'), ('В работе', 'В работе'), ('Модерн', 'Модерн'), ('НеЗаказ', 'НеЗаказ'), ('Готово', 'Готово'), ('Отказ', 'Отказ')], default='Ожидает', max_length=50, verbose_name='Статус'),
        ),
        migrations.AddIndex(
            model_name='phonegoroda',
            index=models.Index(fields=['gorod'], name='core_phoneg_gorod_i_170e80_idx'),
        ),
        migrations.AddField(
            model_name='masterpayout',
            name='zayavka',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payout', to='core.zayavki', verbose_name='Заявка'),
        ),
        migrations.AddIndex(
            model_name='masterpayout',
            index=models.Index(fields=['status'], name='core_master_status_a68cba_idx'),
        ),
        migrations.AddIndex(
            model_name='masterpayout',
            index=models.Index(fields=['created_at'], name='core_master_created_84d837_idx'),
        ),
    ]
