# Generated by Django 5.2.1 on 2025-07-06 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_id', models.IntegerField(verbose_name='ID мастера')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('status', models.CharField(default='pending', max_length=50, verbose_name='Статус')),
                ('payment_method', models.CharField(default='bank', max_length=50, verbose_name='Способ выплаты')),
            ],
            options={
                'verbose_name': 'Выплата',
                'verbose_name_plural': 'Выплаты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TipTranzakcii',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Тип транзакции')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тип транзакции',
                'verbose_name_plural': 'Типы транзакций',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tranzakciya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('status', models.CharField(default='pending', max_length=50, verbose_name='Статус')),
                ('user_id', models.IntegerField(verbose_name='ID пользователя')),
                ('master_id', models.IntegerField(blank=True, null=True, verbose_name='ID мастера')),
                ('zayavka_id', models.IntegerField(blank=True, null=True, verbose_name='ID заявки')),
                ('tip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.tiptranzakcii', verbose_name='Тип транзакции')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'ordering': ['-created_at'],
            },
        ),
    ]
