# Generated by Django 5.2.1 on 2025-07-06 18:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gorod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Roli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название роли')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('passport', models.CharField(blank=True, max_length=50, null=True, verbose_name='Паспорт')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Номер телефона должен быть в формате: +999999999', regex='^\\+?1?\\d{9,15}$')], verbose_name='Номер телефона')),
                ('is_active', models.BooleanField(default=True, verbose_name='Работает')),
                ('chat_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ChatID')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('login', models.CharField(max_length=50, unique=True, verbose_name='Логин')),
                ('password', models.CharField(max_length=100, verbose_name='Пароль')),
                ('gorod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.gorod', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Мастер',
                'verbose_name_plural': 'Мастера',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['gorod', 'is_active'], name='users_maste_gorod_i_5a36dd_idx'), models.Index(fields=['login'], name='users_maste_login_b3ecc8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Polzovateli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус')),
                ('login', models.CharField(max_length=50, unique=True, verbose_name='Логин')),
                ('password', models.CharField(max_length=100, verbose_name='Пароль')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('gorod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.gorod', verbose_name='Город')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.roli', verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['gorod', 'is_active'], name='users_polzo_gorod_i_1a87cb_idx'), models.Index(fields=['login'], name='users_polzo_login_609ac5_idx'), models.Index(fields=['rol'], name='users_polzo_rol_id_777889_idx')],
            },
        ),
    ]
